apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  WEB_ADDRESS: "*"
  WEBSERVER_LOGGER: "true"
  WEBSERVER_PORT: "3000"
  WEBSERVER_ADDRESS: "0.0.0.0"

  MONGO_HOST: mongo-main-0.mongo-service.mongodb.svc.cluster.local,mongo-main-1.mongo-service.mongodb.svc.cluster.local
  MONGO_DB: winget-run-dev
