apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        # set automatically by github actions
        sha: {{ .Values.sha }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .Release.Name }}
        image: docker.pkg.github.com/winget-run/{{ .Release.Name }}/{{ .Release.Name }}:master
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        env:
        - name: MONGO_CERT
          valueFrom:
            secretKeyRef:
              key: MONGO_CERT
              name: {{ .Release.Name }}
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: GITHUB_TOKEN
              name: {{ .Release.Name }}

        - name: WEB_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: WEB_ADDRESS
              name: {{ .Release.Name }}
        - name: WEBSERVER_LOGGER
          valueFrom:
            configMapKeyRef:
              key: WEBSERVER_LOGGER
              name: {{ .Release.Name }}
        - name: WEBSERVER_PORT
          valueFrom:
            configMapKeyRef:
              key: WEBSERVER_PORT
              name: {{ .Release.Name }}
        - name: WEBSERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: WEBSERVER_ADDRESS
              name: {{ .Release.Name }}

        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              key: MONGO_HOST
              name: {{ .Release.Name }}
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              key: MONGO_DB
              name: {{ .Release.Name }}
